### ISSUE TITLE
Error on the Image Processor node

### ISSUE THREAD

**Issue by slimanibenbadis** [Zuellni/ComfyUI-PickScore-Nodes#2]
Hello,

There is an issue when running the workflow.
Here is the error output: 
```
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "E:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\PIL\Image.py", line 3089, in fromarray
    mode, rawmode = _fromarray_typemap[typekey]
                    ~~~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: ((1, 1, 2496, 3), '|u1')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-PickScore-Nodes\pickscore.py", line 46, in process
    processor(
  File "E:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\models\clip\processing_clip.py", line 102, in __call__
    image_features = self.image_processor(images, return_tensors=return_tensors, **kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\image_processing_utils.py", line 446, in __call__
    return self.preprocess(images, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\models\clip\image_processing_clip.py", line 318, in preprocess
    images = [self.resize(image=image, size=size, resample=resample) for image in images]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\models\clip\image_processing_clip.py", line 318, in <listcomp>
    images = [self.resize(image=image, size=size, resample=resample) for image in images]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\models\clip\image_processing_clip.py", line 144, in resize
    return resize(image, size=output_size, resample=resample, data_format=data_format, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\image_transforms.py", line 275, in resize
    image = to_pil_image(image)
            ^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\image_transforms.py", line 163, in to_pil_image
    return PIL.Image.fromarray(image)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\PIL\Image.py", line 3092, in fromarray
    raise TypeError(msg) from e
TypeError: Cannot handle this data type: (1, 1, 2496, 3), |u1
``` 

Thank you for your effort

**Comment by Zuellni** [comment]
Does it happen with the default workflow from readme/every workflow you're running? If not, can you share your workflow and images used (or at least their dimensions) if possible?

**Comment by slimanibenbadis** [comment]
It happen with the default workflow in the readme of this repo. 
I loaded 2 PNG images in the dedicated nodes of this default workflow nothing fancy. Left everything default and it generated this error anyway.

**Comment by Zuellni** [comment]
I tested the workflow with the latest portable ComfyUI build and the example ComfyUI image just now and I'm not seeing any errors so not quite sure what this could be about.

**Comment by slimanibenbadis** [comment]
I will test it on a clean portable version and let you know. 
Maybe a conflict with another custom nodes extension ?

**Comment by slimanibenbadis** [comment]
It works on a clean install without other extensions.

Like I said I think it is some sort of conflict with another extension. I will try adding them one by one and retry until I reproduce the error. 

Quick question though. If I leave the text processor blank, will it select the image with the best overall score ?

**Comment by Zuellni** [comment]
Glad to see it works, let me know what extension is causing trouble and I'll see what I can do about it.

Leaving the prompt blank should be fine since the nodes will calculate the score based on the image embeddings alone in that case but I can't vouch for how accurate the results will be. The Pick-a-Pic paper doesn't seem to mention anything about such usage.
